# -*- coding: utf-8 -*-
"""Final_Project_CSC101.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tHSc1MnhXAvnpmNfQvRAr1C_WYV_9cok
"""

#final project.........................

total_donation = [
    ["Alibaba", "2310001", 100000.0],
    ["Amazon", "2310002", 150000.0],
    ["Uber", "2310003", 200000.0],
    ["UDer", "2310004", 300000.0],
    ["Daraz", "2310005", 0.0],
    ["Grameenphone", "2310006", 0.0],
    ["Vivo", "2310007", 0.0],
    ["Oppo", "2310008", 0.0],
    ["iphone", "2310009", 0.0],
    ["Mi", "2310010", 0.0]
]

def better_formate(x):               #proper formate of the total donation list

  print("{0:15}{1:15}{2:9}".format("Company Name", "ID", "Donation amount"))
  print("{0:15}{1:15}{2:9}".format("------------", "---", "---------------"))
  for i in total_donation:
    if i[2]!=0:
      print("{0:15}{1:15}{2:9}".format(i[0],i[1],i[2]))


def sum_of_the_donation():            #checking the total donation collected from the companies
  sum=0
  index_for_sum=2
  for i in (total_donation):
   sum= sum +i [index_for_sum]
  print(f"Total collected donation is:  {sum} Taka")


def collect_donation():                #collect donation from a company in the existing list
  company_name=input("Enter your company name here: ")
  company_id=input("Enter your company id here: ")

  for i in total_donation:
    if i[0]==company_name and i[1]==company_id:
      collected_money=float(input("""Enter your donation amount(it should be 100k or above): """))
      if collected_money>=100000:
        i[2]+=collected_money

        print(f"""Company name: {company_name} with ID: {company_id} recently donate: {collected_money} Taka.
Thank you for your donation.
Have a nice day sir!!""")
        break
      else:
        print("Sorry, your donation amount must be 100k or above.")
        break
  else:
      print(f"""Sorry. Company name: {company_name} with ID: {company_id} is not found on my system.
First of all press--->(4) to add your company.""")


def non_contributing_companies():          #the list of non-donating companies
  print("{0:15}{1:15}{2:9}".format("Company Name","ID","Donation amount"))
  print("{0:15}{1:15}{2:9}".format("------------", "---", "---------------"))
  for i in total_donation:
    if i[2]==0:
      print("{0:15}{1:15}{2:9}".format(i[0],i[1],i[2]))



def add_new_company():                        #adding new company in the existing list
  name=input("Enter your company or brand name: ")
  id=input("Enter your company ID here: ")
  amount=float(input("Enter your donation amount here(it should be 100k or above): "))
  if amount>=100000:
   total_donation.append([name,id,amount])
   print("""Congratulation!!! You have successfully joined and your donation is successfully received.""")
  else:
    print("your amount is less than 100k")

while(True):                                    # the main menu
  print("Hello Sir/Ma'am, ")
  print("Welcome to you on our donation management site. ")
  print("1-->press for --------> Total Donation ")
  print("2-->press for ----- --> Display Non-Contributing Companies")
  print("3-->press for --------> Collect Donation")
  print("4-->press for --------> Add New Company")
  print("5-->press for --------> Exit")
  print()

  x=input("Enter the number here(1 to 5): ")
  if x == '1':
    better_formate(total_donation)
    sum_of_the_donation()
  elif x == '2':
    non_contributing_companies()
  elif x == '3':
    collect_donation()
  elif x == '4':
    add_new_company()
  elif x == '5':
    print("Thanks, come again.")
    break
  else:
    print("Invlid or working in this site")
    print('Please enter number 1 to 5')

  print()